services:
  - type: web
    name: backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
    startCommand: gunicorn backend.wsgi